# ------------------- WHITELIST -----------------------
whitelist:
  whitelisted-players:
    - Player1
    - Player2
  kick-message: "&cYou are not whitelisted on our server! If you think this is a mistake contact Mrlion!"

# ------- JOIN & QUIT MESSAGES ---------

# Can be used placeholders {player}
join-message: "&6sʏsᴛᴇᴍ &8» &6{player} &7has joined the server!"
quit-message: "&6sʏsᴛᴇᴍ &8» &6{player} &7has left the server :("

#--------- BLOCKED COMMANDS --------
blocked-commands:
  - pl
  - plugins
  - version
  - bukkit:plugins
  - bukkit:pl
  - bukkit:?
  - help
  - bukkit:help
  - about
  - bukkit:about
  - bukkit:ver
  - bukkit:version
blocked-commands-no-perms: "&csʏsᴛᴇᴍ &8» &cYou don't have permission to execute this command!"

# ------- OTHER MESSAGES ---------

msg:
  outgoing-message-format: "&6sʏsᴛᴇᴍ &8» &6{sender} &8-> &6{receiver}&7: &7{message}"
  incoming-message-format: "&6sʏsᴛᴇᴍ &8» &6{sender} &8-> &6You&7: &7{message}"
  usage: "&6sʏsᴛᴇᴍ &8» &cUsage: /msg <player> <message>"
  player-not-found: "&csʏsᴛᴇᴍ &8» &cPlayer not found!"

fly:
  no-permissions: "&csʏsᴛᴇᴍ &8» &cYou don't have permission to use this command!"

reload:
  config-reloaded: "&#D51B21sʏsᴛᴇᴍ &8»&aConfig successfully reloaded!"
  no-permissions: "&#D51B21You don't have permission to use this command."
  error: "&#D51B21An error occurred while reloading the config. See the console for more"

heal:
  no-permissions: "&csʏsᴛᴇᴍ &8» &cYou don't have permission to use this command!"
  self-heal-message: "&asʏsᴛᴇᴍ &8» &aYou have been healed!"
  other-heal-message: "&asʏsᴛᴇᴍ &8» &aYou have been healed by {healer}!"
  all-heal-message: "&asʏsᴛᴇᴍ &8» &aAll players have been healed!"
  player-not-found-message: "&csʏsᴛᴇᴍ &8» &cPlayer not found!"
  console-usage-message: "&csʏsᴛᴇᴍ &8» &cUsage: /heal <player/all>"

ping:
  ping-message: "&6sʏsᴛᴇᴍ &8» &7Your ping is &6{ping}ms"

invalidmessage:
  custom-command-not-found-message: "&cThis command doesn't exist or you don't just have permission for it!"

