name: LionPlugin
author: Mrlion
description: "An utility plugin, made by Mrlion for his server :)"
version: "1.02"
main: me.mrlion.lionplugin.LionPlugin
api-version: '1.20'
resources:
  - config.yml
commands:
  fly:
    description: Toggle flight mode
    usage: /fly
    permission: lionplugin.fly
  heal:
    description: Heals specific player or everyone
    usage: /heal <player/all>
    permission: lionplugin.heal
  msg:
    description: Send a private message a specific player
    usage: /msg <player> <message>
  lionreload:
    description: Reloads config
    usage: /lionreload
    permission: lionplugin.reload
    aliases:
      - lreload
  ping:
    description: Get your ping
    usage: /ping