name: LionPlugin
author: Mrlion
description: "An utility plugin, made by Mrlion for his server :)"
version: "1.02"
main: me.mrlion.lionplugin.LionPlugin
api-version: '1.20'
resources:
  - config.yml
commands:
  fly:
    description: Toggle flight mode
    usage: /fly
  heal:
    description: Heals specific player or everyone
    usage: /heal <player/all>
  msg:
    description: Send a private message a specific player
    usage: /msg <player> <message>
  lreload:
    description: Reloads plugin's config
    usage: /lreload
  ping:
    description: Get your ping
    usage: /ping
permissions:
  lionplugin.*:
    children:
      - lionplugin.fly
      - lionplugin.heal
      - lionplugin.reload
  lionplugin.fly:
    description: Gives permission to use /fly
  lionplugin.heal:
    description: Gives permissions to heal yourself/all/player
  lionplugin.reload:
    description: Gives permission to reload the config.yml