name: LionPlugin
author: Mrlion
description: "An utility plugin, made by Mrlion for his server :)"
version: "BUILD-1426"
main: me.mrlion.lionplugin.LionPlugin
api-version: '1.20'
load: POSTWORLD
resources:
  - config.yml
commands:
  fly:
    description: Toggle flight mode
    usage: /fly
  heal:
    description: Heals you or everyone
    usage: /heal <player/all>
  msg:
    description: Send a private message a specific player
    usage: /msg <player> <message>
  lreload:
    description: Reloads config
    usage: /lreload
  ping:
    description: Get your ping
    usage: /ping