name: LionPlugin
author: Mrlion
description: A utility plugin, made by Mrlion
load: POSTWORLD
version: "BUILD 168"
main: me.mrlion.lionplugin.LionPlugin
api-version: '1.20'
resources:
  - config.yml
commands:
  fly:
    description: Toggle flight mode
    usage: /fly
  heal:
    description: Heals you or everyone
    usage: /heal <player/all>
  msg:
    description: Message a specific player
    usage: /msg <player> <message>
  reload:
    description: Reloads config.yml
    usage: /lreload