name: LionPlugin
author: Mrlion
description: "An utility plugin, made by Mrlion for his servers"
version: "BUILD-203"
main: me.mrlion.lionplugin.LionPlugin
api-version: '1.20'
resources:
  - config.yml
commands:
  fly:
    description: Toggle flight mode
    usage: /fly
  heal:
    description: Heals you or everyone
    usage: /heal <player/all>
  msg:
    description: Message a specific player
    usage: /msg <player> <message>
  lreload:
    description: Reloads config.yml
    usage: /lreload
  lwhitelist:
    description: Add player to our own whitelist
    usage: /lwhitelist <player>
  ping:
    description: Get your ping
    usage: /ping
  vanish:
    description: Hide you from other players
    usage: /vanish